/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ec.edu.espe.ehamanagement.view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class PnlUpdate extends javax.swing.JPanel {

    /**
     * Creates new form PnlUpdate
     */
    public PnlUpdate() {
        initComponents();
        btnSave.setEnabled(false);
    }

    public void validateFields()
    {

        if (txtEmail.getText().equals("name@gmail.com"))
        {
            lbWarningEmail.setText("this area is required");
            pictureWarningEmail();
        } 
        else 
        {
            if (txtEmail.getText().equals("")) 
            {
                pictureWhiteEmail();
                lbWarningEmail.setText("");

            } 
            else 
            {

                if (!txtEmail.getText().contains("@") || !txtEmail.getText().contains("."))
                {
                    lbWarningEmail.setText("enter a valid email");
                    pictureWarningEmail();
                } else
                {
                    lbWarningEmail.setText("");
                    pictureWhiteEmail();
                }
            }

        }
        if (txtPassword.getText().equals("***************"))
        {
            lbWarningPass.setText("this area is required");
            pictureWarningPassword();
        } else 
        {
            lbWarningPass.setText("");
            pictureWhitePassword();
        }
         if (txtCurrentSalary.getText().equals("$00.00") || txtPassword.getText().equals("***************") || lbWarningEmail.getText().equals("enter a valid email")
            || txtEmail.getText().equals("name@gmail.com") || txtUserName.getText().equals("NameUser") || txtUserName.getText().isEmpty() || txtPassword.getText().isEmpty() || txtEmail.getText().isEmpty()
             || txtCurrentSalary.getText().isEmpty()) {
         btnSave.setEnabled(false);
        } else {
            btnSave.setEnabled(true);
       }

    }

    

    public void pictureWarningUser() {
        lbValidateUserPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/alert.png"))); // NOI18N
        lbValidateUserPicture.setText("");
    }

    public void pictureWhiteUser() {
        lbValidateUserPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/picture1.png"))); // NOI18N
        lbValidateUserPicture.setText("");
    }

    public void pictureWarningPassword() {
        lbValidatePassPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/alert.png"))); // NOI18N
        lbValidatePassPicture.setText("");
    }

    public void pictureWhitePassword() {
        lbValidatePassPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/picture1.png"))); // NOI18N
        lbValidatePassPicture.setText("");
    }

    public void pictureWarningEmail() {
        lbValidateEmailPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/alert.png"))); // NOI18N
        lbValidateEmailPicture.setText("");
    }

    public void pictureWhiteEmail() {
        lbValidateEmailPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/picture1.png"))); // NOI18N
        lbValidateEmailPicture.setText("");
    }

    public void pictureWarningSalary() {
        lbValidateCurrentSPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/alert.png"))); // NOI18N
        lbValidateCurrentSPicture.setText("");
    }

    public void pictureWhiteSalary() {
        lbValidateCurrentSPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/picture1.png"))); // NOI18N
        lbValidateCurrentSPicture.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        lbValidatePassPicture = new javax.swing.JLabel();
        lbValidateUserPicture = new javax.swing.JLabel();
        lbValidateEmailPicture = new javax.swing.JLabel();
        lbValidateCurrentSPicture = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCurrentSalary = new javax.swing.JTextField();
        lbWarningCurrentS = new javax.swing.JLabel();
        lbWarningPass = new javax.swing.JLabel();
        lbWarningEmail = new javax.swing.JLabel();
        lbWarningUser = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUserName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("User");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Email");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Current Salary");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setText("name@gmail.com");
        txtEmail.setBorder(null);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEmailMousePressed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        txtCurrentSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCurrentSalary.setForeground(new java.awt.Color(153, 153, 153));
        txtCurrentSalary.setText("$00.00");
        txtCurrentSalary.setBorder(null);
        txtCurrentSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCurrentSalaryMousePressed(evt);
            }
        });
        txtCurrentSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentSalaryActionPerformed(evt);
            }
        });
        txtCurrentSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCurrentSalaryKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurrentSalaryKeyTyped(evt);
            }
        });

        lbWarningCurrentS.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbWarningCurrentS.setForeground(new java.awt.Color(204, 0, 0));

        lbWarningPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbWarningPass.setForeground(new java.awt.Color(204, 0, 0));

        lbWarningEmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbWarningEmail.setForeground(new java.awt.Color(204, 0, 0));

        lbWarningUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbWarningUser.setForeground(new java.awt.Color(204, 0, 0));

        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("***************");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtUserName.setText("UserName");
        txtUserName.setBorder(null);
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUserNameMousePressed(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(102, 255, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCurrentSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUserName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbValidateEmailPicture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbValidateCurrentSPicture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbValidatePassPicture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValidateUserPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbWarningCurrentS, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWarningEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWarningPass, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbWarningUser, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbValidateUserPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbWarningUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValidateEmailPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWarningEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValidateCurrentSPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrentSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWarningCurrentS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbValidatePassPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWarningPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCurrentSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentSalaryActionPerformed

    private void txtEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMousePressed
        if (txtEmail.getText().equals("name@gmail.com")) {
            txtEmail.setText("");
            txtEmail.setForeground(Color.black);

        }
        if (txtUserName.getText().isEmpty()) {
            txtUserName.setText("UserName");
            txtUserName.setForeground(Color.gray);

        }

        if (String.valueOf(txtPassword.getPassword()).isEmpty()) {
            txtPassword.setText("***************");
            txtPassword.setForeground(Color.gray);

        }
        if (txtCurrentSalary.getText().isEmpty()) {
            txtCurrentSalary.setText("$00.00");
            txtCurrentSalary.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtEmailMousePressed

    private void txtCurrentSalaryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCurrentSalaryMousePressed
        if (txtCurrentSalary.getText().equals("$00.00")) {
            txtCurrentSalary.setText("");
            txtCurrentSalary.setForeground(Color.black);
        }
        if (txtUserName.getText().isEmpty()) {
            txtUserName.setText("UserName");
            txtUserName.setForeground(Color.gray);

        }
        if (String.valueOf(txtPassword.getPassword()).isEmpty()) {
            txtPassword.setText("***************");
            txtPassword.setForeground(Color.gray);

        }
        if (txtEmail.getText().isEmpty()) {
            txtEmail.setText("name@gmail.com");
            txtEmail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCurrentSalaryMousePressed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        if (String.valueOf(txtPassword.getPassword()).equals("***************")) {
            txtPassword.setText("");
            txtPassword.setForeground(Color.black);

        }
        if (txtUserName.getText().isEmpty()) {
            txtUserName.setText("UserName");
            txtUserName.setForeground(Color.gray);
        }
        if (txtEmail.getText().isEmpty()) {
            txtEmail.setText("name@gmail.com");
            txtEmail.setForeground(Color.gray);
        }
        if (txtCurrentSalary.getText().isEmpty()) {
            txtCurrentSalary.setText("$00.00");
            txtCurrentSalary.setForeground(Color.gray);

        }
    }//GEN-LAST:event_txtPasswordMousePressed

    private void txtUserNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMousePressed
        if (txtUserName.getText().equals("UserName")) {
            txtUserName.setText("");

            txtUserName.setForeground(Color.black);

        }

        if (txtCurrentSalary.getText().isEmpty()) {
            txtCurrentSalary.setText("$00.00");
            txtCurrentSalary.setForeground(Color.gray);

        }
        if (String.valueOf(txtPassword.getPassword()).isEmpty()) {
            txtPassword.setText("***************");
            txtPassword.setForeground(Color.gray);

        }
        if (txtEmail.getText().isEmpty()) {
            txtEmail.setText("name@gmail.com");
            txtEmail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUserNameMousePressed

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
        char c = evt.getKeyChar();
        if (txtUserName.getText().equals("UserName")) {
            lbWarningUser.setText("this area is required");
            pictureWarningUser();
        } else {
            if (!Character.isLetter(c) && (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_SPACE)) {
                getToolkit().beep();
                evt.consume();
                pictureWarningUser();
                lbWarningUser.setText(c + " is not accepted here!");

            } else {
                lbWarningUser.setText("");
                pictureWhiteUser();
            }

        }
    }//GEN-LAST:event_txtUserNameKeyTyped

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        validateFields();
        if (txtCurrentSalary.getText().equals("$00.00")) {
            lbWarningCurrentS.setText("this area is required");
            pictureWarningSalary();
        } else {
            lbValidateCurrentSPicture.setText("");
            pictureWhiteSalary();
        }
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        if (txtUserName.getText().equals("UserName")) {
            lbWarningUser.setText("this area is required ");
            pictureWarningUser();
        } else {
            lbWarningUser.setText("");
            pictureWhiteUser();
        }
        if (txtCurrentSalary.getText().equals("$00.00")) {
            lbWarningCurrentS.setText("this area is required");
            pictureWarningSalary();
        } else {
            lbWarningCurrentS.setText("");
            pictureWhiteSalary();
        }
        validateFields();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        if (txtUserName.getText().equals("UserName")) {
            lbWarningUser.setText("this area is required");
            pictureWarningUser();
        } else {
            lbWarningUser.setText("");
            pictureWhiteUser();
        }
        if (txtCurrentSalary.getText().equals("$00.00")) {
            lbWarningCurrentS.setText("this area is required");
            pictureWarningSalary();
        } else {
            lbWarningCurrentS.setText("");
            pictureWhiteSalary();
        }
        validateFields();
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtCurrentSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurrentSalaryKeyReleased
        if (txtUserName.getText().equals("UserName")) {
            lbWarningUser.setText("this area is required");
            pictureWarningUser();
        } else {
            lbWarningUser.setText("");
            pictureWhiteUser();
        }
        validateFields();
    }//GEN-LAST:event_txtCurrentSalaryKeyReleased

    private void txtCurrentSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurrentSalaryKeyTyped
        char c = evt.getKeyChar();

        if (txtCurrentSalary.getText().equals("$00.00")) {
            lbWarningCurrentS.setText("this area is required");
            pictureWarningSalary();
        } else {
            if (!Character.isDigit(c) && (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_PERIOD)) {
                //getToolkit().beep();
                evt.consume();
                pictureWarningSalary();
                lbWarningCurrentS.setText(c + " is not accepted here");
            } else {
                lbWarningCurrentS.setText("");
                pictureWhiteSalary();
            }

        }
    }//GEN-LAST:event_txtCurrentSalaryKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
     int option = JOptionPane.showConfirmDialog(this, "Do you want to update ?");        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbValidateCurrentSPicture;
    private javax.swing.JLabel lbValidateEmailPicture;
    private javax.swing.JLabel lbValidatePassPicture;
    private javax.swing.JLabel lbValidateUserPicture;
    private javax.swing.JLabel lbWarningCurrentS;
    private javax.swing.JLabel lbWarningEmail;
    private javax.swing.JLabel lbWarningPass;
    private javax.swing.JLabel lbWarningUser;
    private javax.swing.JTextField txtCurrentSalary;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
