package ec.edu.espe.ehamanagement.view;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import com.mongodb.client.MongoCollection;
import ec.edu.espe.ehamanagement.controller.Agenda;
import ec.edu.espe.ehamanagement.controller.Inventory;
import ec.edu.espe.ehamanagement.controller.MaterialsOrganizer;
import ec.edu.espe.ehamanagement.controller.Profile;
import java.awt.BorderLayout;
/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class FrmPrincipalMenuBar extends javax.swing.JFrame {
    private final MongoCollection productsCollection;
    private final MongoCollection userCollection;
    private final MongoCollection ordersCollection;
    private final MongoCollection materialsCollection;
    /**
     * Creates new form FrmAbout2
     */
    public FrmPrincipalMenuBar(){
        productsCollection = Inventory.createConnectionToCollection();
        userCollection = Profile.createConnectionToCollection();
        ordersCollection = Agenda.createConnectionToCollection();
        materialsCollection = MaterialsOrganizer.createConnectionToCollection();
        initComponents();
        initPnlStartPage();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initPnlStartPage(){
        PnlStartPage pnlStartPage = new PnlStartPage(productsCollection, ordersCollection);
        pnlStartPage.setSize(980,540);
        pnlStartPage.setLocation(0,0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlStartPage, BorderLayout.CENTER);
        PnlWindow.revalidate();
        PnlWindow.repaint();
    }
    private void initPnlAbout(){
        PnlAbout pnlAbout = new PnlAbout();
        pnlAbout.setSize(932,525);
        pnlAbout.setLocation(20,0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlAbout, BorderLayout.CENTER);
        PnlWindow.revalidate();
        PnlWindow.repaint();
    }
    
    private void initPnlContactUs(){
        PnlContactUs pnlContactUs = new PnlContactUs();
        pnlContactUs.setSize(980,523);
        pnlContactUs.setLocation(0,0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlContactUs, BorderLayout.CENTER);
        PnlWindow.revalidate();
        PnlWindow.repaint();
    }
    private void initFrmProfile(){
        this.setVisible(false);
        FrmProfile frmProfile = new FrmProfile(userCollection);
        frmProfile.setVisible(true);
    }
    private void initPnlAgenda(){
        PnlAgenda pnlAgenda = new PnlAgenda(ordersCollection);
        pnlAgenda.setSize(980,629);
        pnlAgenda.setLocation(0,0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlAgenda, pnlAgenda);
        PnlWindow.revalidate();
        PnlWindow.repaint();    
    }
   
    private void initPnlInventory(){
        PnlInventory pnlInventory = new PnlInventory(productsCollection, materialsCollection, userCollection);
        pnlInventory.setSize(996, 623);
        pnlInventory.setLocation(0,0);
        
        PnlWindow.removeAll();
        PnlWindow.add(pnlInventory, BorderLayout.CENTER);
        PnlWindow.revalidate();
        PnlWindow.repaint();    
    }
    public void initOrganizer()
    {
        PnlOrganizer pnlOrganizer = new PnlOrganizer(materialsCollection);
        pnlOrganizer.setSize(980, 629);
        pnlOrganizer.setLocation(0,0);
        
        PnlWindow.removeAll();
        PnlWindow.add(pnlOrganizer, BorderLayout.CENTER);
        PnlWindow.revalidate();
        PnlWindow.repaint();
             
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlWindow = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnEHA = new javax.swing.JMenu();
        mnuActions = new javax.swing.JMenu();
        mnuProfile = new javax.swing.JMenuItem();
        mnuInventory = new javax.swing.JMenuItem();
        mnuAgenda = new javax.swing.JMenuItem();
        mnuMaterialsOrganizer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        MnHelp = new javax.swing.JMenu();
        mnuContactUs = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlWindow.setBackground(new java.awt.Color(255, 255, 255));
        PnlWindow.setMaximumSize(new java.awt.Dimension(980, 629));
        PnlWindow.setMinimumSize(new java.awt.Dimension(980, 629));
        PnlWindow.setPreferredSize(new java.awt.Dimension(980, 629));

        javax.swing.GroupLayout PnlWindowLayout = new javax.swing.GroupLayout(PnlWindow);
        PnlWindow.setLayout(PnlWindowLayout);
        PnlWindowLayout.setHorizontalGroup(
            PnlWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        PnlWindowLayout.setVerticalGroup(
            PnlWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 153));

        MnEHA.setText("Entre Hilos & Algodon");
        MnEHA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MnEHA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnEHAMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MnEHAMousePressed(evt);
            }
        });
        MnEHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnEHAActionPerformed(evt);
            }
        });
        jMenuBar1.add(MnEHA);

        mnuActions.setText("Actions");
        mnuActions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuActionsMouseClicked(evt);
            }
        });

        mnuProfile.setText("Profile");
        mnuProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuProfileMousePressed(evt);
            }
        });
        mnuActions.add(mnuProfile);

        mnuInventory.setText("Inventory");
        mnuInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuInventoryMousePressed(evt);
            }
        });
        mnuActions.add(mnuInventory);

        mnuAgenda.setText("Agenda");
        mnuAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuAgendaMousePressed(evt);
            }
        });
        mnuActions.add(mnuAgenda);

        mnuMaterialsOrganizer.setText("MaterialsOrganizer");
        mnuMaterialsOrganizer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuMaterialsOrganizer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuMaterialsOrganizerMousePressed(evt);
            }
        });
        mnuActions.add(mnuMaterialsOrganizer);

        jMenu2.setText("Reports");

        jMenuItem4.setText("General Report");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Inventory Report");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Agenda Report");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(jMenuItem6);

        mnuActions.add(jMenu2);

        jMenuBar1.add(mnuActions);

        MnHelp.setText("Help");
        MnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mnuContactUs.setText("Contact Us");
        mnuContactUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuContactUsMousePressed(evt);
            }
        });
        MnHelp.add(mnuContactUs);

        mnuAbout.setText("About Entre Hilos & Algodón Management Software");
        mnuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuAboutMousePressed(evt);
            }
        });
        MnHelp.add(mnuAbout);

        jMenuBar1.add(MnHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnEHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnEHAActionPerformed
        
    }//GEN-LAST:event_MnEHAActionPerformed

    private void MnEHAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnEHAMouseClicked

    }//GEN-LAST:event_MnEHAMouseClicked

    private void mnuActionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuActionsMouseClicked

        
    }//GEN-LAST:event_mnuActionsMouseClicked

    private void mnuProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuProfileMousePressed
        initFrmProfile();
    }//GEN-LAST:event_mnuProfileMousePressed

    private void mnuInventoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuInventoryMousePressed
         initPnlInventory();
    }//GEN-LAST:event_mnuInventoryMousePressed

    private void mnuAgendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAgendaMousePressed
          initPnlAgenda();
    }//GEN-LAST:event_mnuAgendaMousePressed

    private void mnuMaterialsOrganizerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMaterialsOrganizerMousePressed
        initOrganizer();
    }//GEN-LAST:event_mnuMaterialsOrganizerMousePressed

    private void mnuAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAboutMousePressed
       initPnlAbout();
    }//GEN-LAST:event_mnuAboutMousePressed

    private void MnEHAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnEHAMousePressed
        initPnlStartPage();
    }//GEN-LAST:event_MnEHAMousePressed

    private void mnuContactUsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuContactUsMousePressed
       initPnlContactUs();
    }//GEN-LAST:event_mnuContactUsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalMenuBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnEHA;
    private javax.swing.JMenu MnHelp;
    private javax.swing.JPanel PnlWindow;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuActions;
    private javax.swing.JMenuItem mnuAgenda;
    private javax.swing.JMenuItem mnuContactUs;
    private javax.swing.JMenuItem mnuInventory;
    private javax.swing.JMenuItem mnuMaterialsOrganizer;
    private javax.swing.JMenuItem mnuProfile;
    // End of variables declaration//GEN-END:variables
}
