package ec.edu.espe.ehamanagement.view;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import ec.edu.espe.ehamanagement.view.panels.PnlAbout;
import java.awt.BorderLayout;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class FrmPrincipalMenuBar extends javax.swing.JFrame {

    /**
     * Creates new form FrmAbout2
     */
    public FrmPrincipalMenuBar() 
    {
        initComponents();
        InitContent();
        initAgendaMenuOption();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void InitContent()
    {
        PnlAbout pnlAbout = new PnlAbout();
        pnlAbout.setSize(932,525);
        pnlAbout.setLocation(0,0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlAbout, BorderLayout.CENTER);
        PnlWindow.revalidate();
        PnlWindow.repaint();
    }
    private void initAgendaMenuOption(){
        PnlAgendaMenuOption pnlAgendaMenuOption = new PnlAgendaMenuOption();
        pnlAgendaMenuOption.setSize(1000,650);
        pnlAgendaMenuOption.setLocation(0,0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlAgendaMenuOption, pnlAgendaMenuOption);
        PnlWindow.revalidate();
        PnlWindow.repaint();    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlWindow = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnEHA = new javax.swing.JMenu();
        MnProfile = new javax.swing.JMenu();
        MnInventory = new javax.swing.JMenu();
        MnAgenda = new javax.swing.JMenu();
        MnMaterialsOrganizer = new javax.swing.JMenu();
        MnReport = new javax.swing.JMenu();
        MnHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlWindow.setBackground(new java.awt.Color(255, 255, 255));
        PnlWindow.setPreferredSize(new java.awt.Dimension(929, 470));

        javax.swing.GroupLayout PnlWindowLayout = new javax.swing.GroupLayout(PnlWindow);
        PnlWindow.setLayout(PnlWindowLayout);
        PnlWindowLayout.setHorizontalGroup(
            PnlWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        PnlWindowLayout.setVerticalGroup(
            PnlWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 153));

        MnEHA.setText("Entre Hilos & Algodon");
        MnEHA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MnEHA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnEHAMouseClicked(evt);
            }
        });
        MnEHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnEHAActionPerformed(evt);
            }
        });
        jMenuBar1.add(MnEHA);

        MnProfile.setText("Profile");
        MnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnProfileMouseClicked(evt);
            }
        });
        jMenuBar1.add(MnProfile);

        MnInventory.setText("Inventory");
        MnInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(MnInventory);

        MnAgenda.setText("Agenda");
        MnAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MnAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnAgendaMouseClicked(evt);
            }
        });
        jMenuBar1.add(MnAgenda);

        MnMaterialsOrganizer.setText("Materials Organizer");
        MnMaterialsOrganizer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(MnMaterialsOrganizer);

        MnReport.setText("Report");
        jMenuBar1.add(MnReport);

        MnHelp.setText("Help");
        MnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(MnHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlWindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnEHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnEHAActionPerformed
        
    }//GEN-LAST:event_MnEHAActionPerformed

    private void MnEHAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnEHAMouseClicked
        InitContent();
    }//GEN-LAST:event_MnEHAMouseClicked

    private void MnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnProfileMouseClicked
        this.setVisible(false);
        FrmProfile frmProfile = new FrmProfile();
        frmProfile.setVisible(true);
    }//GEN-LAST:event_MnProfileMouseClicked

    private void MnAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnAgendaMouseClicked
        initAgendaMenuOption();
    }//GEN-LAST:event_MnAgendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalMenuBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnAgenda;
    private javax.swing.JMenu MnEHA;
    private javax.swing.JMenu MnHelp;
    private javax.swing.JMenu MnInventory;
    private javax.swing.JMenu MnMaterialsOrganizer;
    private javax.swing.JMenu MnProfile;
    private javax.swing.JMenu MnReport;
    private javax.swing.JPanel PnlWindow;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
