package ec.edu.espe.ehamanagement.view;

/**
 *
 * @author NicolayChillo Gaman GeekLords at DCOO-ESPE
 */
public class PnlAgendaMenuOption extends javax.swing.JPanel {

    /**
     * Creates new form PnlAgendaMenuOption
     */
    public PnlAgendaMenuOption() {
        initComponents();
        initPnlOptionMenuSearch();
        initPnlNewOrder();
        initPnlTablePendingOrders();
        initPnlTableDeliveredOrders();
        initPnlTableAllOrders();
        
        BtnGrOrderTables.add(RabtnAllOrders);
        BtnGrOrderTables.add(RabtnDeliveredOrders);
        BtnGrOrderTables.add(RabtnPendingOrders);
        
    }
    private void initPnlTableAllOrders(){
        PnlTableAllOrders pnlTableAllOrders = new PnlTableAllOrders();
        pnlTableAllOrders.setSize(1000,600);
        pnlTableAllOrders.setLocation(0, 0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlTableAllOrders,pnlTableAllOrders);
        PnlWindow.revalidate();
        PnlWindow.repaint();
    }
    private void initPnlTableDeliveredOrders(){
        PnlTableDeliveredOrders pnlDeliveredOrders = new PnlTableDeliveredOrders();
        pnlDeliveredOrders.setSize(1000,650);
        pnlDeliveredOrders.setLocation(0, 0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlDeliveredOrders,pnlDeliveredOrders);
        PnlWindow.revalidate();
        PnlWindow.repaint();
    }
    private void initPnlTablePendingOrders(){
        PnlTablePendingOrders pnlTablePendingOrders = new PnlTablePendingOrders();
        pnlTablePendingOrders.setSize(1000,650);
        pnlTablePendingOrders.setLocation(0, 0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlTablePendingOrders,pnlTablePendingOrders);
        PnlWindow.revalidate();
        PnlWindow.repaint();
    }
    private void initPnlOptionMenuSearch(){
        PnlOptionMenuSearch pnlOptionMenuSearch = new PnlOptionMenuSearch();
        pnlOptionMenuSearch.setSize(1000,650);
        pnlOptionMenuSearch.setLocation(0, 0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlOptionMenuSearch,pnlOptionMenuSearch);
        PnlWindow.revalidate();
        PnlWindow.repaint();
    }
    private void initPnlNewOrder(){
        PnlNewOrder pnlNewOrder = new PnlNewOrder();
        pnlNewOrder.setSize(1000,650);
        pnlNewOrder.setLocation(0, 0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlNewOrder,pnlNewOrder);
        PnlWindow.revalidate();
        PnlWindow.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGrOrderTables = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        BtnAddOrder = new javax.swing.JButton();
        BtnSearch = new javax.swing.JButton();
        RabtnAllOrders = new javax.swing.JRadioButton();
        RabtnDeliveredOrders = new javax.swing.JRadioButton();
        RabtnPendingOrders = new javax.swing.JRadioButton();
        BtnRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnlWindow = new javax.swing.JPanel();

        setBackground(new java.awt.Color(252, 154, 11));
        setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel2.setBackground(new java.awt.Color(80, 22, 2));
        jPanel2.setToolTipText("");

        BtnAddOrder.setBackground(new java.awt.Color(183, 96, 9));
        BtnAddOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnAddOrder.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddOrder.setText("Add Order");
        BtnAddOrder.setBorder(null);
        BtnAddOrder.setBorderPainted(false);
        BtnAddOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddOrderMouseClicked(evt);
            }
        });

        BtnSearch.setBackground(new java.awt.Color(183, 96, 9));
        BtnSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        BtnSearch.setText("Search");
        BtnSearch.setBorder(null);
        BtnSearch.setBorderPainted(false);
        BtnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSearchMouseClicked(evt);
            }
        });
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        BtnGrOrderTables.add(RabtnAllOrders);
        RabtnAllOrders.setForeground(new java.awt.Color(255, 255, 255));
        RabtnAllOrders.setText("All Orders");
        RabtnAllOrders.setBorder(null);
        RabtnAllOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RabtnAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RabtnAllOrdersActionPerformed(evt);
            }
        });

        BtnGrOrderTables.add(RabtnDeliveredOrders);
        RabtnDeliveredOrders.setForeground(new java.awt.Color(255, 255, 255));
        RabtnDeliveredOrders.setText("Delivered Orders");
        RabtnDeliveredOrders.setBorder(null);

        BtnGrOrderTables.add(RabtnPendingOrders);
        RabtnPendingOrders.setForeground(new java.awt.Color(255, 255, 255));
        RabtnPendingOrders.setText("Pending Orders");
        RabtnPendingOrders.setBorder(null);

        BtnRefresh.setBackground(new java.awt.Color(183, 96, 9));
        BtnRefresh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        BtnRefresh.setText("Refresh");
        BtnRefresh.setBorder(null);
        BtnRefresh.setBorderPainted(false);
        BtnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRefreshMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnAddOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RabtnDeliveredOrders)
                    .addComponent(RabtnAllOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RabtnPendingOrders, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(RabtnAllOrders)
                .addGap(18, 18, 18)
                .addComponent(RabtnDeliveredOrders)
                .addGap(18, 18, 18)
                .addComponent(RabtnPendingOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jPanel1.setBackground(new java.awt.Color(80, 22, 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        PnlWindow.setBackground(new java.awt.Color(252, 154, 11));
        PnlWindow.setPreferredSize(new java.awt.Dimension(1000, 650));

        javax.swing.GroupLayout PnlWindowLayout = new javax.swing.GroupLayout(PnlWindow);
        PnlWindow.setLayout(PnlWindowLayout);
        PnlWindowLayout.setHorizontalGroup(
            PnlWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        PnlWindowLayout.setVerticalGroup(
            PnlWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(PnlWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddOrderMouseClicked
        initPnlNewOrder();
    }//GEN-LAST:event_BtnAddOrderMouseClicked

    private void BtnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSearchMouseClicked
        initPnlOptionMenuSearch();
    }//GEN-LAST:event_BtnSearchMouseClicked

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed

    }//GEN-LAST:event_BtnSearchActionPerformed

    private void BtnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRefreshMouseClicked
        if(RabtnAllOrders.isSelected()){
            initPnlTableAllOrders();
        }if(RabtnDeliveredOrders.isSelected()){
            initPnlTableDeliveredOrders();
        }if(RabtnPendingOrders.isSelected()){
            initPnlTablePendingOrders();
        }
    }//GEN-LAST:event_BtnRefreshMouseClicked

    private void RabtnAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RabtnAllOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RabtnAllOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddOrder;
    private javax.swing.ButtonGroup BtnGrOrderTables;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JPanel PnlWindow;
    private javax.swing.JRadioButton RabtnAllOrders;
    private javax.swing.JRadioButton RabtnDeliveredOrders;
    private javax.swing.JRadioButton RabtnPendingOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
