/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ec.edu.espe.ehamanagement.view;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class PnlShowFindInformation extends javax.swing.JPanel {

    /**
     * Creates new form PnlShowFindInformation
     */
    DefaultTableModel modelTable;
    public PnlShowFindInformation() {
        initComponents();
        modelTable = new DefaultTableModel();
        modelTable.addColumn("ID");
        modelTable.addColumn("Name");
        modelTable.addColumn("Cost");
        modelTable.addColumn("Stock");
        this.tblInventory.setModel(modelTable);
        btnFind.setEnabled(false);
    }
    private void cleanTable() {
        int row = tblInventory.getRowCount();
        for (int i = row - 1; i >= 0; i--) {
            modelTable.removeRow(i);
        }
    }
    private void refresTable()
    {
        if (rbtnAllProducts.isSelected()) {
            cleanTable();
            lblTableTitle.setText("All Orders");
            
        } else if (rbtnProductsStock.isSelected()) {
            lblTableTitle.setText("Products in stock");
            cleanTable();
            
        } else if (rbtnProductsInShortage.isSelected()) {
            lblTableTitle.setText("Products in shortage");
            cleanTable();
           
        }
    }
     
    private void InitContentTable()
    {
        PnlUpdateAndDeleteProducts pnlAddProductAgenda = new PnlUpdateAndDeleteProducts();
        pnlAddProductAgenda.setSize(713,528);
        pnlAddProductAgenda.setLocation(0,0);
        pnlContent.removeAll();
        pnlContent.add(pnlAddProductAgenda, pnlAddProductAgenda);
        pnlContent.revalidate();
        pnlContent.repaint();
        
    }
    private void validateDates() {

        if (!txtSearch.getText().isEmpty() && !txtSearch.getText().equals("Search...")) {
            btnFind.setEnabled(true);
        } else {
            btnFind.setEnabled(false);
        }
    }
    private void pictureWarningSearch() {
        lblPictureWarning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/alert.png"))); // NOI18N
        lblPictureWarning.setText("");
    }

    public void pictureWhiteSearch() {
        lblPictureWarning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/whiteSeen.png"))); // NOI18N
        lblPictureWarning.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupProducts = new javax.swing.ButtonGroup();
        btnGroupSearch = new javax.swing.ButtonGroup();
        pnlContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        rbtnAllProducts = new javax.swing.JRadioButton();
        rbtnProductsStock = new javax.swing.JRadioButton();
        rbtnProductsInShortage = new javax.swing.JRadioButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTableTitle = new javax.swing.JLabel();
        rbtnSearchId = new javax.swing.JRadioButton();
        rbtnSearchName = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnFind = new javax.swing.JButton();
        lblPictureWarning = new javax.swing.JLabel();
        lblTextWarning = new javax.swing.JLabel();

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));

        tblInventory.setBackground(new java.awt.Color(199, 123, 213));
        tblInventory.setForeground(new java.awt.Color(204, 153, 255));
        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInventory);

        btnGrupProducts.add(rbtnAllProducts);
        rbtnAllProducts.setSelected(true);
        rbtnAllProducts.setText("All Products");
        rbtnAllProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAllProductsActionPerformed(evt);
            }
        });

        btnGrupProducts.add(rbtnProductsStock);
        rbtnProductsStock.setText("Products in stock");
        rbtnProductsStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnProductsStockActionPerformed(evt);
            }
        });

        btnGrupProducts.add(rbtnProductsInShortage);
        rbtnProductsInShortage.setText("Products in shortage");
        rbtnProductsInShortage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnProductsInShortageActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(129, 87, 154));
        btnRefresh.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Search Product");

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTableTitle.setText("All Products");

        btnGroupSearch.add(rbtnSearchId);
        rbtnSearchId.setText("By ID");
        rbtnSearchId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnSearchIdMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnSearchIdMousePressed(evt);
            }
        });
        rbtnSearchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSearchIdActionPerformed(evt);
            }
        });

        btnGroupSearch.add(rbtnSearchName);
        rbtnSearchName.setText("By Name");
        rbtnSearchName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnSearchNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnSearchNameMousePressed(evt);
            }
        });

        txtSearch.setText("Search...");
        txtSearch.setBorder(null);
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSearchMousePressed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        btnFind.setBackground(new java.awt.Color(129, 87, 154));
        btnFind.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnFind.setForeground(new java.awt.Color(255, 255, 255));
        btnFind.setText("Find");
        btnFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFindMouseClicked(evt);
            }
        });
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        lblTextWarning.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTextWarning.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(lblTableTitle))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(rbtnAllProducts)
                        .addGap(29, 29, 29)
                        .addComponent(rbtnProductsStock)
                        .addGap(42, 42, 42)
                        .addComponent(rbtnProductsInShortage))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(rbtnSearchId)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(rbtnSearchName)
                        .addGap(32, 32, 32)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPictureWarning)
                                .addGap(29, 29, 29)
                                .addComponent(lblTextWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTableTitle)
                .addGap(7, 7, 7)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnAllProducts)
                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnProductsStock)
                        .addComponent(rbtnProductsInShortage))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlContentLayout.createSequentialGroup()
                            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPictureWarning)
                                .addComponent(lblTextWarning))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlContentLayout.createSequentialGroup()
                            .addComponent(rbtnSearchId)
                            .addGap(18, 18, 18)
                            .addComponent(rbtnSearchName)))
                    .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 490, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnSearchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSearchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSearchIdActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
      InitContentTable();
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindMouseClicked
        
    }//GEN-LAST:event_btnFindMouseClicked

    private void txtSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMousePressed
        if (txtSearch.getText().equals("Search...")) {
            txtSearch.setText("");
        }

    }//GEN-LAST:event_txtSearchMousePressed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        char character = evt.getKeyChar();
        if (txtSearch.getText().equals("Search...")) {
            lblTextWarning.setText(" requiered to search");
            pictureWarningSearch();
        }else{
            if (rbtnSearchName.isSelected() && !Character.isLetter(character) && (character != KeyEvent.VK_BACK_SPACE && character != KeyEvent.VK_SPACE)) 
            {
                evt.consume();
                pictureWarningSearch();
                lblTextWarning.setText(character + " is not accepted here!");
            }else{
                if (rbtnSearchId.isSelected() && !Character.isDigit(character) && (character != KeyEvent.VK_BACK_SPACE )) {
                    evt.consume();
                    pictureWarningSearch();
                    lblTextWarning.setText(character + " is not accepted here!");
                }else{

                    lblTextWarning.setText("");
                    pictureWhiteSearch();

                }
            }
        }
    }//GEN-LAST:event_txtSearchKeyTyped

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        validateDates();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void rbtnSearchIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnSearchIdMouseClicked
        txtSearch.setText("Search...");
        if (txtSearch.getText().equals("Search...")||txtSearch.getText().equals("")) {
            lblTextWarning.setText(" requiered to search");
            pictureWarningSearch();
        } else {
            lblTextWarning.setText("");
        }
    }//GEN-LAST:event_rbtnSearchIdMouseClicked

    private void rbtnSearchIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnSearchIdMousePressed
        txtSearch.setText("Search...");
        if (txtSearch.getText().isEmpty()) {
            txtSearch.setText("Search...");
        }
    }//GEN-LAST:event_rbtnSearchIdMousePressed

    private void rbtnSearchNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnSearchNameMouseClicked
        txtSearch.setText("Search...");
        if (txtSearch.getText().equals("Search...")) {
            lblTextWarning.setText(" requiered to search");
            pictureWarningSearch();
        } else {
            lblTextWarning.setText("");
        }
    }//GEN-LAST:event_rbtnSearchNameMouseClicked

    private void rbtnSearchNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnSearchNameMousePressed
        txtSearch.setText("Search...");
        if (txtSearch.getText().isEmpty()) {
            txtSearch.setText("Search...");
        }
    }//GEN-LAST:event_rbtnSearchNameMousePressed

    private void rbtnProductsInShortageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnProductsInShortageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnProductsInShortageActionPerformed

    private void rbtnProductsStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnProductsStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnProductsStockActionPerformed

    private void rbtnAllProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAllProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAllProductsActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refresTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.ButtonGroup btnGroupSearch;
    private javax.swing.ButtonGroup btnGrupProducts;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPictureWarning;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblTextWarning;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JRadioButton rbtnAllProducts;
    private javax.swing.JRadioButton rbtnProductsInShortage;
    private javax.swing.JRadioButton rbtnProductsStock;
    private javax.swing.JRadioButton rbtnSearchId;
    private javax.swing.JRadioButton rbtnSearchName;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
