/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ec.edu.espe.ehamanagement.view;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class PnlShowFindInformation extends javax.swing.JPanel {

    /**
     * Creates new form PnlShowFindInformation
     */
    DefaultTableModel modelTable;
    public PnlShowFindInformation() {
        initComponents();
        modelTable = new DefaultTableModel();
        modelTable.addColumn("ID");
        modelTable.addColumn("Name");
        modelTable.addColumn("Until Cost");
        
        this.tblMaterial.setModel(modelTable);
        btnFind.setEnabled(false);
    }
    
    
     
    private void InitContentTable()
    {
        PnlUpdateAndDeleteMaterial pnlUpdateAndDeleteMaterial = new PnlUpdateAndDeleteMaterial();
        pnlUpdateAndDeleteMaterial.setSize(720,486);
        pnlUpdateAndDeleteMaterial.setLocation(0,0);
        pnlContent.removeAll();
        pnlContent.add(pnlUpdateAndDeleteMaterial,pnlUpdateAndDeleteMaterial );
        pnlContent.revalidate();
        pnlContent.repaint();
        
    }
    private void validateDates() {

        if (!txtSearch.getText().isEmpty() && !txtSearch.getText().equals("Search...")) {
            btnFind.setEnabled(true);
        } else {
            btnFind.setEnabled(false);
        }
    }
    private void pictureWarningSearch() {
        lblPictureWarning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/alert.png"))); // NOI18N
        lblPictureWarning.setText("");
    }

    public void pictureWhiteSearch() {
        lblPictureWarning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/whiteSeen.png"))); // NOI18N
        lblPictureWarning.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupProducts = new javax.swing.ButtonGroup();
        btnGroupSearch = new javax.swing.ButtonGroup();
        pnlContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTableTitle = new javax.swing.JLabel();
        rbtnSearchId = new javax.swing.JRadioButton();
        rbtnSearchName = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblPictureWarning = new javax.swing.JLabel();
        lblTextWarning = new javax.swing.JLabel();

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));

        tblMaterial.setBackground(new java.awt.Color(102, 255, 102));
        tblMaterial.setForeground(new java.awt.Color(204, 153, 255));
        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tblMaterial);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Search Material");

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTableTitle.setText("Materials Organizer");

        btnGroupSearch.add(rbtnSearchId);
        rbtnSearchId.setText("By ID");
        rbtnSearchId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnSearchIdMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnSearchIdMousePressed(evt);
            }
        });
        rbtnSearchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSearchIdActionPerformed(evt);
            }
        });

        btnGroupSearch.add(rbtnSearchName);
        rbtnSearchName.setText("By Name");
        rbtnSearchName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnSearchNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnSearchNameMousePressed(evt);
            }
        });

        txtSearch.setText("Search...");
        txtSearch.setBorder(null);
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSearchMousePressed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        btnFind.setBackground(new java.awt.Color(112, 172, 61));
        btnFind.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnFind.setForeground(new java.awt.Color(255, 255, 255));
        btnFind.setText("Find");
        btnFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFindMouseClicked(evt);
            }
        });
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        lblPictureWarning.setText("5");

        lblTextWarning.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTextWarning.setText("5");

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(lblTableTitle))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnSearchId)
                                    .addComponent(rbtnSearchName))
                                .addGap(32, 32, 32)
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlContentLayout.createSequentialGroup()
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlContentLayout.createSequentialGroup()
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPictureWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTextWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(rbtnSearchId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnSearchName))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPictureWarning)
                            .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextWarning)))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnSearchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSearchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSearchIdActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
      
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindMouseClicked
        InitContentTable();
    }//GEN-LAST:event_btnFindMouseClicked

    private void txtSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMousePressed
        if (txtSearch.getText().equals("Search...")) {
            txtSearch.setText("");
        }

    }//GEN-LAST:event_txtSearchMousePressed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        char character = evt.getKeyChar();
        if (txtSearch.getText().equals("Search...")) {
            lblTextWarning.setText(" requiered to search");
            pictureWarningSearch();
        }else{
            if (rbtnSearchName.isSelected() && !Character.isLetter(character) && (character != KeyEvent.VK_BACK_SPACE && character != KeyEvent.VK_SPACE)) 
            {
                evt.consume();
                pictureWarningSearch();
                lblTextWarning.setText(character + " is not accepted here!");
            }else{
                if (rbtnSearchId.isSelected() && !Character.isDigit(character) && (character != KeyEvent.VK_BACK_SPACE )) {
                    evt.consume();
                    pictureWarningSearch();
                    lblTextWarning.setText(character + " is not accepted here!");
                }else{

                    lblTextWarning.setText("");
                    pictureWhiteSearch();

                }
            }
        }
    }//GEN-LAST:event_txtSearchKeyTyped

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        validateDates();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void rbtnSearchIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnSearchIdMouseClicked
        txtSearch.setText("Search...");
        if (txtSearch.getText().equals("Search...")||txtSearch.getText().equals("")) {
            lblTextWarning.setText(" requiered to search");
            pictureWarningSearch();
        } else {
            lblTextWarning.setText("");
        }
    }//GEN-LAST:event_rbtnSearchIdMouseClicked

    private void rbtnSearchIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnSearchIdMousePressed
        txtSearch.setText("Search...");
        if (txtSearch.getText().isEmpty()) {
            txtSearch.setText("Search...");
        }
    }//GEN-LAST:event_rbtnSearchIdMousePressed

    private void rbtnSearchNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnSearchNameMouseClicked
        txtSearch.setText("Search...");
        if (txtSearch.getText().equals("Search...")) {
            lblTextWarning.setText(" requiered to search");
            pictureWarningSearch();
        } else {
            lblTextWarning.setText("");
        }
    }//GEN-LAST:event_rbtnSearchNameMouseClicked

    private void rbtnSearchNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnSearchNameMousePressed
        txtSearch.setText("Search...");
        if (txtSearch.getText().isEmpty()) {
            txtSearch.setText("Search...");
        }
    }//GEN-LAST:event_rbtnSearchNameMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.ButtonGroup btnGroupSearch;
    private javax.swing.ButtonGroup btnGrupProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPictureWarning;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblTextWarning;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JRadioButton rbtnSearchId;
    private javax.swing.JRadioButton rbtnSearchName;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
