/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ec.edu.espe.ehamanagement.view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class PnlUpdateAndDeleteMaterial extends javax.swing.JPanel {

    /**
     * Creates new form PnlMenu
     */
    public PnlUpdateAndDeleteMaterial() {
        initComponents();
        DisabledButtons();

    }

    public void DisabledButtons() {

        txtMaterialName.setEnabled(false);
        txtUnitCost.setEnabled(false);
        txtxGeneralCost.setEnabled(false);

        spnQuantity.setEnabled(false);//
        //btnDelete.setEnabled(false);
        btnSave.setEnabled(false);

    }

    public void validateDates() {
        /* if (txtMaterialName.getText().isEmpty()) {
            lblTextWarning.setText("Campo obligatorio");
            pictureWarningProduct();
        } else {
            lblTextWarning.setText("");
            pictureWhiteProduct();
        }
        if (txtDescription.getText().isEmpty()) {
            
            pictureWarningArea();
        } else {
            
            pictureWhiteArea();
        }*/

        if (txtMaterialName.getText().isEmpty() || txtUnitCost.getText().isEmpty() || txtUnitCost.getText().equals("$ 0.00") || (txtxGeneralCost.getText().isEmpty()
                || txtxGeneralCost.getText().equals("0.00") || txtMaterialName.getText().equals("Name"))) {
            btnSave.setEnabled(false);
        } else {
            btnSave.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        lbProductName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spnQuantity = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtMaterialName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtxGeneralCost = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUnitCost = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblPictureWarning = new javax.swing.JLabel();
        lblTxtWarning = new javax.swing.JLabel();
        lblPicturGeneralCost = new javax.swing.JLabel();
        lblTextGeneralCost = new javax.swing.JLabel();
        lblPictureUnitCost = new javax.swing.JLabel();
        lblTextUnitCost = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setPreferredSize(new java.awt.Dimension(720, 523));

        lbProductName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbProductName.setText("Materials Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Quantity");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("$");

        txtMaterialName.setText("Name");
        txtMaterialName.setBorder(null);
        txtMaterialName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMaterialNameMousePressed(evt);
            }
        });
        txtMaterialName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaterialNameActionPerformed(evt);
            }
        });
        txtMaterialName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaterialNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaterialNameKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(52, 122, 52));

        btnUpdate.setBackground(new java.awt.Color(112, 172, 61));
        btnUpdate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(112, 172, 61));
        btnDelete.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(35, 35, 35)
                .addComponent(btnDelete)
                .addGap(156, 156, 156))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("General Cost");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("untils");

        txtxGeneralCost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtxGeneralCost.setText("0.00");
        txtxGeneralCost.setBorder(null);
        txtxGeneralCost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtxGeneralCostMousePressed(evt);
            }
        });
        txtxGeneralCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtxGeneralCostKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtxGeneralCostKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Unit Cost");

        txtUnitCost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUnitCost.setText("$ 0.00");
        txtUnitCost.setBorder(null);
        txtUnitCost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUnitCostMousePressed(evt);
            }
        });
        txtUnitCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUnitCostKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnitCostKeyTyped(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        lblPictureWarning.setText("jLabel5");

        lblTxtWarning.setText("jLabel7");

        lblPicturGeneralCost.setText("jLabel5");

        lblTextGeneralCost.setForeground(new java.awt.Color(255, 0, 0));
        lblTextGeneralCost.setText("jLabel7");

        lblPictureUnitCost.setText("jLabel5");

        lblTextUnitCost.setForeground(new java.awt.Color(255, 0, 0));
        lblTextUnitCost.setText("jLabel7");

        btnSave.setBackground(new java.awt.Color(112, 172, 61));
        btnSave.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(txtUnitCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addComponent(txtMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lblPictureWarning)
                                .addGap(18, 18, 18)
                                .addComponent(lblTxtWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPictureUnitCost)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlContentLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtxGeneralCost, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblPicturGeneralCost)
                                .addGap(23, 23, 23)
                                .addComponent(lblTextGeneralCost, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblTextUnitCost, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbProductName)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProductName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPictureWarning)
                    .addComponent(lblTxtWarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(txtxGeneralCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(lblPicturGeneralCost)
                            .addComponent(lblTextGeneralCost))))
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnitCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPictureUnitCost)
                            .addComponent(lblTextUnitCost))
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnSave))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaterialNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaterialNameKeyReleased
        validateDates();
    }//GEN-LAST:event_txtMaterialNameKeyReleased
    private void pictureWarningMaterial() {
        lblPictureWarning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/alert.png"))); // NOI18N
        lblPictureWarning.setText("");
    }

    private void pictureWhiteMaterial() {
        lblPictureWarning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/whiteSeen.png"))); // NOI18N
        lblPictureWarning.setText("");
    }

    private void pictureWarningGeneralCost() {
        lblPicturGeneralCost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/alert.png"))); // NOI18N
        lblPictureWarning.setText("");
    }

    private void pictureWhiteGeneralCost() {
        lblPicturGeneralCost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/whiteSeen.png"))); // NOI18N
        lblPictureWarning.setText("");
    }

    private void pictureWarningUnitCost() {
        lblPictureUnitCost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/alert.png"))); // NOI18N
        lblPictureUnitCost.setText("");
    }

    private void pictureWhiteUnitCost() {
        lblPictureUnitCost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec.edu.espe.ehamanagement.picture/whiteSeen.png"))); // NOI18N
        lblPictureUnitCost.setText("");
    }

    private void txtMaterialNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaterialNameMousePressed
        if (!btnUpdate.isEnabled()) {
            if (txtxGeneralCost.getText().isEmpty()) {
                txtxGeneralCost.setText("0.00");
            }
            if (txtUnitCost.getText().isEmpty()) {
                txtUnitCost.setText("$ 0.00");
            }
            if (txtMaterialName.getText().equals("Name")) {
                txtMaterialName.setText("");
            }

        }


    }//GEN-LAST:event_txtMaterialNameMousePressed

    private void txtMaterialNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaterialNameKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_SPACE)) {
            //getToolkit().beep();
            evt.consume();
            pictureWarningMaterial();
            lblTxtWarning.setText(c + " is not accepted here!");

        } else {
            lblTxtWarning.setText("");
            pictureWhiteMaterial();
        }
    }//GEN-LAST:event_txtMaterialNameKeyTyped

    private void txtxGeneralCostMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtxGeneralCostMousePressed
        if (!btnUpdate.isEnabled()) {

            if (txtUnitCost.getText().equals("")) {
                txtUnitCost.setText("$ 0.00");
                //txtxGeneralCost.setText("");
            }
            if (txtxGeneralCost.getText().equals("0.00")) {
                txtxGeneralCost.setText("");
            }
            if (txtMaterialName.getText().isEmpty()) {
                txtMaterialName.setText("Name");
            }

        }

    }//GEN-LAST:event_txtxGeneralCostMousePressed

    private void txtUnitCostMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnitCostMousePressed
        if (!btnUpdate.isEnabled()) {

            if (txtxGeneralCost.getText().equals("")) {
                txtxGeneralCost.setText("0.00");

            }
            if (txtUnitCost.getText().equals("$ 0.00")) {
                txtUnitCost.setText("");
            }
            if (txtMaterialName.getText().isEmpty()) {
                txtMaterialName.setText("Name");
            }

        }

    }//GEN-LAST:event_txtUnitCostMousePressed

    private void txtUnitCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnitCostKeyReleased
        validateDates();
    }//GEN-LAST:event_txtUnitCostKeyReleased

    private void txtUnitCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnitCostKeyTyped
        char character = evt.getKeyChar();
        if (!Character.isDigit(character) && (character != KeyEvent.VK_BACK_SPACE) && (character != KeyEvent.VK_PERIOD)) {
            evt.consume();
            pictureWarningUnitCost();
            lblTextUnitCost.setText(character + " is not accepted here!");
        } else {

            lblTextUnitCost.setText("");
            pictureWhiteUnitCost();
        }
    }//GEN-LAST:event_txtUnitCostKeyTyped

    private void txtxGeneralCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtxGeneralCostKeyTyped
        char character = evt.getKeyChar();
        if (!Character.isDigit(character) && (character != KeyEvent.VK_BACK_SPACE) && (character != KeyEvent.VK_PERIOD)) {
            evt.consume();
            pictureWarningGeneralCost();
            lblTextGeneralCost.setText(character + " is not accepted here!");
        } else {

            lblTextGeneralCost.setText("");
            pictureWhiteGeneralCost();
        }
    }//GEN-LAST:event_txtxGeneralCostKeyTyped

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        int option = JOptionPane.showConfirmDialog(null, "Are your dure you want to delete this material?");
        if (option == 0) {
            JOptionPane.showMessageDialog(null, "removed materials");
            btnUpdate.setEnabled(false);
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        txtUnitCost.setEnabled(true);
        txtxGeneralCost.setEnabled(true);
        spnQuantity.setEnabled(true);
        // validateDates();

        spnQuantity.setEnabled(true); //

        txtxGeneralCost.setEnabled(true);//
        spnQuantity.setEnabled(true);//

        txtMaterialName.setEnabled(true);
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void txtxGeneralCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtxGeneralCostKeyReleased
        validateDates();
    }//GEN-LAST:event_txtxGeneralCostKeyReleased

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        int option = JOptionPane.showConfirmDialog(null, "Are your dure you want to update this material?");
        if (option == 0) {
            JOptionPane.showMessageDialog(null, "updated  materials");

        }
    }//GEN-LAST:event_btnSaveMouseClicked

    private void txtMaterialNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaterialNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaterialNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbProductName;
    private javax.swing.JLabel lblPicturGeneralCost;
    private javax.swing.JLabel lblPictureUnitCost;
    private javax.swing.JLabel lblPictureWarning;
    private javax.swing.JLabel lblTextGeneralCost;
    private javax.swing.JLabel lblTextUnitCost;
    private javax.swing.JLabel lblTxtWarning;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextField txtMaterialName;
    private javax.swing.JTextField txtUnitCost;
    private javax.swing.JTextField txtxGeneralCost;
    // End of variables declaration//GEN-END:variables
}
