/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package espe.edu.ec.HandicraftShop.view;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;

import java.awt.Color;
import java.awt.Image;
import java.awt.TextField;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class SingIn extends javax.swing.JFrame {

    /**
     * Creates new form SingIn
     */
    public  SingIn()
    {
        initComponents();
        btnSend.setEnabled(false);
        
    }
    
    public void validateFields() {
        
        if (txtfNameEmail.getText().equals("name@gmail.com")) {
            lbEmailValidation.setText("this area is required");
            pictureWarningEmail();
        } else {
            if (txtfNameEmail.getText().equals("")) {
                pictureWhiteEmail();
                lbEmailValidation.setText("");

            } else {

                if (!txtfNameEmail.getText().contains("@") || !txtfNameEmail.getText().contains(".")) {
                    lbEmailValidation.setText("invalid mail");
                    pictureWarningEmail();
                } else {
                    lbEmailValidation.setText("");
                    pictureWhiteEmail();
                }
            }

        }
        if (txtNamePassword.getText().equals("***************")) {
            lbPasswordValidation.setText("this area is required");
            pictureWarningPassword();
        } else {
            lbPasswordValidation.setText("");
            pictureWhitePassword();
        }

        if (txtfNameCurrentSalary.getText().equals("write your current salary ") || txtNamePassword.getText().equals("***************") || lbEmailValidation.getText().equals("invalid mail")
                || txtfNameEmail.getText().equals("name@gmail.com") || txtfNameUser.getText().equals("Enter your username ") || txtfNameUser.getText().isEmpty() || txtNamePassword.getText().isEmpty() || txtfNameEmail.getText().isEmpty()
                || txtfNameCurrentSalary.getText().isEmpty()) {
            btnSend.setEnabled(false);
        } else {
            btnSend.setEnabled(true);
        }

    }

    public void pictureWarningUser() {
        lbPictureWarningUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alert.png"))); // NOI18N
        lbPictureWarningUser.setText("");
    }

    public void pictureWhiteUser() {
        lbPictureWarningUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture1.png"))); // NOI18N
        lbPictureWarningUser.setText("");
    }

    public void pictureWarningPassword() {
        lbPictureWarningPasd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alert.png"))); // NOI18N
        lbPictureWarningPasd.setText("");
    }

    public void pictureWhitePassword() {
        lbPictureWarningPasd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture1.png"))); // NOI18N
        lbPictureWarningPasd.setText("");
    }

    public void pictureWarningEmail() {
        lbPictureWarningMail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alert.png"))); // NOI18N
        lbPictureWarningMail1.setText("");
    }

    public void pictureWhiteEmail() {
        lbPictureWarningMail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture1.png"))); // NOI18N
        lbPictureWarningMail1.setText("");
    }

    public void pictureWarningSalary() {
        lbPictureWarningSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alert.png"))); // NOI18N
        lbPictureWarningSalary.setText("");
    }

    public void pictureWhiteSalary() {
        lbPictureWarningSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture1.png"))); // NOI18N
        lbPictureWarningSalary.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbUser1 = new javax.swing.JLabel();
        txtfNameUser = new javax.swing.JTextField();
        sptLine = new javax.swing.JSeparator();
        lbEmail = new javax.swing.JLabel();
        txtfNameEmail = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lbPassword = new javax.swing.JLabel();
        txtNamePassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        lbCurrentSalary = new javax.swing.JLabel();
        txtfNameCurrentSalary = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnSend = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbEmailValidation = new javax.swing.JLabel();
        lbUserValidation = new javax.swing.JLabel();
        lbPasswordValidation = new javax.swing.JLabel();
        lbSalaryValidation = new javax.swing.JLabel();
        lbPictureWarningUser = new javax.swing.JLabel();
        lbPictureWarningPasd = new javax.swing.JLabel();
        lbPictureWarningSalary = new javax.swing.JLabel();
        lbPictureWarningMail1 = new javax.swing.JLabel();
        btnClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Log in");

        lbUser1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbUser1.setText("User");

        txtfNameUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfNameUser.setForeground(new java.awt.Color(204, 204, 204));
        txtfNameUser.setText("Enter your username  ");
        txtfNameUser.setBorder(null);
        txtfNameUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtfNameUserMousePressed(evt);
            }
        });
        txtfNameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNameUserActionPerformed(evt);
            }
        });
        txtfNameUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfNameUserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfNameUserKeyTyped(evt);
            }
        });

        lbEmail.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbEmail.setText("E-mail ");

        txtfNameEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfNameEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtfNameEmail.setText("name@gmail.com");
        txtfNameEmail.setBorder(null);
        txtfNameEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtfNameEmailMousePressed(evt);
            }
        });
        txtfNameEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNameEmailActionPerformed(evt);
            }
        });
        txtfNameEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfNameEmailKeyReleased(evt);
            }
        });

        lbPassword.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbPassword.setText("Password");

        txtNamePassword.setForeground(new java.awt.Color(204, 204, 204));
        txtNamePassword.setText("***************");
        txtNamePassword.setBorder(null);
        txtNamePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNamePasswordMousePressed(evt);
            }
        });
        txtNamePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamePasswordActionPerformed(evt);
            }
        });
        txtNamePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamePasswordKeyReleased(evt);
            }
        });

        lbCurrentSalary.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbCurrentSalary.setText("Current salary");

        txtfNameCurrentSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfNameCurrentSalary.setForeground(new java.awt.Color(204, 204, 204));
        txtfNameCurrentSalary.setText("write your current salary ");
        txtfNameCurrentSalary.setBorder(null);
        txtfNameCurrentSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtfNameCurrentSalaryMousePressed(evt);
            }
        });
        txtfNameCurrentSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNameCurrentSalaryActionPerformed(evt);
            }
        });
        txtfNameCurrentSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfNameCurrentSalaryKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfNameCurrentSalaryKeyTyped(evt);
            }
        });

        btnSend.setBackground(new java.awt.Color(0, 51, 204));
        btnSend.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSend.setText("Send");
        btnSend.setBorder(null);
        btnSend.setBorderPainted(false);
        btnSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cityA.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favicon.png"))); // NOI18N

        lbEmailValidation.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lbEmailValidation.setForeground(new java.awt.Color(255, 0, 51));
        lbEmailValidation.setText("5");

        lbUserValidation.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lbUserValidation.setForeground(new java.awt.Color(255, 0, 51));
        lbUserValidation.setText("5");

        lbPasswordValidation.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lbPasswordValidation.setForeground(new java.awt.Color(255, 0, 51));
        lbPasswordValidation.setText("5");

        lbSalaryValidation.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lbSalaryValidation.setForeground(new java.awt.Color(255, 0, 51));
        lbSalaryValidation.setText("5");

        lbPictureWarningUser.setText("jLabel5");

        lbPictureWarningPasd.setText("jLabel5");

        lbPictureWarningSalary.setText("jLabel5");

        lbPictureWarningMail1.setText("jLabel5");

        btnClean.setBackground(new java.awt.Color(0, 51, 255));
        btnClean.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClean.setText("Clean");
        btnClean.setBorder(null);
        btnClean.setBorderPainted(false);
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbUser1)
                                    .addComponent(lbEmail)
                                    .addComponent(lbPassword)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                    .addComponent(jSeparator4)
                                    .addComponent(lbCurrentSalary)
                                    .addComponent(jSeparator2)
                                    .addComponent(sptLine)
                                    .addComponent(txtNamePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfNameCurrentSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbPictureWarningPasd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbPasswordValidation, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbPictureWarningSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbSalaryValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbPictureWarningMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbEmailValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbPictureWarningUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(lbUserValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtfNameUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfNameEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(221, 221, 221)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbUser1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPictureWarningUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUserValidation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sptLine, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfNameEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmailValidation)
                    .addComponent(lbPictureWarningMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPasswordValidation)
                    .addComponent(lbPictureWarningPasd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lbCurrentSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPictureWarningSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfNameCurrentSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSalaryValidation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfNameUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfNameUserMousePressed
        if (txtfNameUser.getText().equals("Enter your username ")) {
            txtfNameUser.setText("");

            txtfNameUser.setForeground(Color.black);

        }

        if (txtfNameCurrentSalary.getText().isEmpty()) {
            txtfNameCurrentSalary.setText("write your current salary ");
            txtfNameCurrentSalary.setForeground(Color.gray);

        }
        if (String.valueOf(txtNamePassword.getPassword()).isEmpty()) {
            txtNamePassword.setText("***************");
            txtNamePassword.setForeground(Color.gray);

        }
        if (txtfNameEmail.getText().isEmpty()) {
            txtfNameEmail.setText("name@gmail.com");
            txtfNameEmail.setForeground(Color.gray);
        }
        //validateFields();

    }//GEN-LAST:event_txtfNameUserMousePressed

    private void txtfNameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNameUserActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtfNameUserActionPerformed

    private void txtfNameEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfNameEmailMousePressed
        if (txtfNameEmail.getText().equals("name@gmail.com")) {
            txtfNameEmail.setText("");
            txtfNameEmail.setForeground(Color.black);

        }
        if (txtfNameUser.getText().isEmpty()) {
            txtfNameUser.setText("Enter your username ");
            txtfNameUser.setForeground(Color.gray);

        }

        if (String.valueOf(txtNamePassword.getPassword()).isEmpty()) {
            txtNamePassword.setText("***************");
            txtNamePassword.setForeground(Color.gray);

        }
        if (txtfNameCurrentSalary.getText().isEmpty()) {
            txtfNameCurrentSalary.setText("write your current salary ");
            txtfNameCurrentSalary.setForeground(Color.gray);

        }
        //validateFields();

    }//GEN-LAST:event_txtfNameEmailMousePressed

    private void txtfNameEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNameEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNameEmailActionPerformed

    private void txtNamePasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamePasswordMousePressed
        if (String.valueOf(txtNamePassword.getPassword()).equals("***************")) {
            txtNamePassword.setText("");
            txtNamePassword.setForeground(Color.black);

        }
        if (txtfNameUser.getText().isEmpty()) {
            txtfNameUser.setText("Enter your username ");
            txtfNameUser.setForeground(Color.gray);
        }
        if (txtfNameEmail.getText().isEmpty()) {
            txtfNameEmail.setText("name@gmail.com");
            txtfNameEmail.setForeground(Color.gray);
        }
        if (txtfNameCurrentSalary.getText().isEmpty()) {
            txtfNameCurrentSalary.setText("write your current salary ");
            txtfNameCurrentSalary.setForeground(Color.gray);

        }
        //validateFields();

    }//GEN-LAST:event_txtNamePasswordMousePressed

    private void txtfNameCurrentSalaryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfNameCurrentSalaryMousePressed
        if (txtfNameCurrentSalary.getText().equals("write your current salary ")) {
            txtfNameCurrentSalary.setText("");
            txtfNameCurrentSalary.setForeground(Color.black);
        }
        if (txtfNameUser.getText().isEmpty()) {
            txtfNameUser.setText("Enter your username ");
            txtfNameUser.setForeground(Color.gray);

        }
        if (String.valueOf(txtNamePassword.getPassword()).isEmpty()) {
            txtNamePassword.setText("***************");
            txtNamePassword.setForeground(Color.gray);

        }
        if (txtfNameEmail.getText().isEmpty()) {
            txtfNameEmail.setText("name@gmail.com");
            txtfNameEmail.setForeground(Color.gray);
        }
        //validateFields();
    }//GEN-LAST:event_txtfNameCurrentSalaryMousePressed

    private void txtfNameCurrentSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNameCurrentSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNameCurrentSalaryActionPerformed

    private void txtfNameUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfNameUserKeyTyped
        char c = evt.getKeyChar();
        if (txtfNameUser.getText().equals("Enter your username ")) {
            lbUserValidation.setText("this area is required");
            pictureWarningUser();
        } else 
        {
            if (!Character.isLetter(c) && (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_SPACE)) {
            //getToolkit().beep();
            evt.consume();
            pictureWarningUser();
            lbUserValidation.setText(c + " is not accepted here!");
            
        } else {
            lbUserValidation.setText("");
            pictureWhiteUser();
        }
            
            
        }
        


    }//GEN-LAST:event_txtfNameUserKeyTyped

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        
        
        int option = JOptionPane.showConfirmDialog(this, "Do you want to continue?");
        JOptionPane.showMessageDialog(this, option);
        

    }//GEN-LAST:event_btnSendActionPerformed

    private void txtNamePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamePasswordActionPerformed

    private void txtfNameUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfNameUserKeyReleased
         

        validateFields();
        if (txtfNameCurrentSalary.getText().equals("write your current salary ")) 
        {
            lbSalaryValidation.setText("this area is required");
            pictureWarningSalary();
        } else
        {
           lbSalaryValidation.setText("");
           pictureWhiteSalary();  
        }
    }//GEN-LAST:event_txtfNameUserKeyReleased

    private void txtfNameCurrentSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfNameCurrentSalaryKeyTyped
        char c = evt.getKeyChar();

        if (txtfNameCurrentSalary.getText().equals("write your current salary ")) 
        {
            lbSalaryValidation.setText("this area is required");
            pictureWarningSalary();
        }
        else
        {
            if (!Character.isDigit(c) && (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_PERIOD)) {
                //getToolkit().beep();
                evt.consume();
                pictureWarningSalary();
                lbSalaryValidation.setText(c + " is not accepted here!");
            }
            else
            {
               lbSalaryValidation.setText("");
               pictureWhiteSalary(); 
            }
            
        }
        

    }//GEN-LAST:event_txtfNameCurrentSalaryKeyTyped

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtfNameCurrentSalary.setText("write your current salary ");
        txtfNameUser.setText("Enter your username ");
        txtNamePassword.setText("***************");
        txtfNameEmail.setText("name@gmail.com");

        txtfNameCurrentSalary.setForeground(Color.gray);
        txtfNameUser.setForeground(Color.gray);
        txtNamePassword.setForeground(Color.gray);
        txtfNameEmail.setForeground(Color.gray);
    }//GEN-LAST:event_btnCleanActionPerformed

    private void txtfNameEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfNameEmailKeyReleased
        if (txtfNameUser.getText().equals("Enter your username ")) {
            lbUserValidation.setText("this area is required");
            pictureWarningUser();
        } else 
        {
            lbUserValidation.setText("");
            pictureWhiteUser();
        }
        if (txtfNameCurrentSalary.getText().equals("write your current salary ")) 
        {
            lbSalaryValidation.setText("this area is required");
            pictureWarningSalary();
        } else
        {
           lbSalaryValidation.setText("");
           pictureWhiteSalary();  
        }
        validateFields();
    }//GEN-LAST:event_txtfNameEmailKeyReleased

    private void txtNamePasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamePasswordKeyReleased
        if (txtfNameUser.getText().equals("Enter your username ")) {
            lbUserValidation.setText("this area is required");
            pictureWarningUser();
        } else 
        {
            lbUserValidation.setText("");
            pictureWhiteUser();
        }
        if (txtfNameCurrentSalary.getText().equals("write your current salary ")) 
        {
            lbSalaryValidation.setText("this area is required");
            pictureWarningSalary();
        } else
        {
           lbSalaryValidation.setText("");
           pictureWhiteSalary();  
        }
        validateFields();
    }//GEN-LAST:event_txtNamePasswordKeyReleased

    private void txtfNameCurrentSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfNameCurrentSalaryKeyReleased
        if (txtfNameUser.getText().equals("Enter your username ")) {
            lbUserValidation.setText("this area is required");
            pictureWarningUser();
        } else 
        {
            lbUserValidation.setText("");
            pictureWhiteUser();
        }
        validateFields();
    }//GEN-LAST:event_txtfNameCurrentSalaryKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbCurrentSalary;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailValidation;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPasswordValidation;
    private javax.swing.JLabel lbPictureWarningMail1;
    private javax.swing.JLabel lbPictureWarningPasd;
    private javax.swing.JLabel lbPictureWarningSalary;
    private javax.swing.JLabel lbPictureWarningUser;
    private javax.swing.JLabel lbSalaryValidation;
    private javax.swing.JLabel lbUser1;
    private javax.swing.JLabel lbUserValidation;
    private javax.swing.JSeparator sptLine;
    private javax.swing.JPasswordField txtNamePassword;
    private javax.swing.JTextField txtfNameCurrentSalary;
    private javax.swing.JTextField txtfNameEmail;
    private javax.swing.JTextField txtfNameUser;
    // End of variables declaration//GEN-END:variables
}
